#' Process SEM effects output for OE,MMI, EPT relabel variable names to make into a table
#'
#' @param sem_output SEM estimated effects output saved as .csv file
#'
#' @return Processed dataframe that selected direct, indirect, and total effects
#' @export
#'
#' @examples xer_oe_m2_full<- sem_eff_tab("model2") # name dataframe loaded with raw SEM effects output

sem_eff_tab_v2 = function(sem_output){
  sem_out_proc <- sem_output %>%
    filter(op==":="|op=="~"&lhs=="OE_SCORE"|op=="~"&lhs=="MMI_BENT_sc"|
             op=="~"&lhs=="EPT_RICH_sc")%>%
    select(lhs,label,est.std,se, pvalue,ci.lower, ci.upper)%>%
    rename(Predictor = label)%>%
    mutate(across(where(is.numeric), round,2))%>%
    mutate(lhs = case_when(str_detect(lhs,"OE_SCORE")~"Direct",
                           str_detect(lhs, "MMI_BENT_sc")~"Direct",
                           str_detect(lhs,"EPT_RICH_sc")~"Direct",
                           str_detect(lhs,"_oe") ~ "Indirect",
                           str_detect(lhs,"_mmi") ~ "Indirect",
                           str_detect(lhs,"_ept") ~ "Indirect",
                           str_detect(lhs,"_tot") ~ "Total",
                           str_detect(lhs, "_xcmgwtot") ~ "Total XCMGW",
                           str_detect(lhs,"_tntot") ~ "Total TN",
                           str_detect(lhs,"_rbstot") ~ "Total RBS",
                           str_detect(lhs,"_sulftot") ~ "Total SO4",
                           str_detect(lhs,"_evtot") ~ "Total Evap",
                           str_detect(lhs,"_lftot") ~ "Total Low flow",
                           str_detect(lhs,"_bftot") ~ "Total Bankfull flow",
                           str_detect(lhs,"_oelflowtot") ~ "Total OE Low flow",
                           str_detect(lhs,"_oebflowtot") ~ "Total OE Bankfull flow",
                           str_detect(lhs,"_sptot") ~ "Total Specific power"))%>%
    mutate(Predictor = recode_factor(Predictor,
                                     a1="Agriculture Ws",u1="Developed CAT",d1="Dam stor Ws",i1="Impervious Rp-Cat",sd1="Slope*depth",r1="Relative bed stability",
                                     c1="Critical diameter",md1="Mean diameter",sf1="Sands/fines",sp1="Specific stream power",
                                     f1="Forest Rp",w1="Wetland Rp-W", rn1="Forest/Grass Rp-CAT",l1="Summer flow",loe1="OE Summer flow",b1="Bankfull flow",boe1="OE Bankfull flow",
                                     x1="Site-riparian cover index",xn1="Instream cover",hh1="Habitat richness",xi1="Channel incision",
                                     ha1="Ag index Rp-S", na1="Non-ag index Rp-S", p1="Precipitation",t1="Max temp", ph1="Drought index",
                                     n1="TN",su1="Sulfate", tu1="Turbidity",
                                     agr_oe="Agriculture Ws",urb_oe="Developed CAT",imp_oe="Impervious Rp-Cat",
                                     graz_oe="Grazing habitat Cat",
                                     rfor_oe="Forest Rp",
                                     rwet_oe="Wetland Rp-W",
                                     rnat_oe="Forest/Grass Rp-CAT",
                                     dam_oe="Dam stor Ws",slope_oe="Slope*depth",strpwr_oe="Specific stream power",
                                     hag_oe="Ag index Rp-S",nhag_oe="Non-ag index Rp-S",
                                     precip_oe="Precipitation",tmax_oe="Max temp",
                                     phdi_oe="Drought index",
                                     dexcess_oe="Evaporation indicator",lflow_oe="Summer flow",
                                     bflow_oe="Bankfull flow",oelflow_oe="OE Summer flow",oebflow_oe="OE Bankfull flow",
                                     xcmgw_oe="Site-riparian cover index",xinc_oe="Channel incision",
                                     agr_mmi="Agriculture Ws",urb_mmi="Developed CAT",imp_mmi="Impervious Rp-Cat",
                                     rfor_mmi="Forest Rp",
                                     rwet_mmi="Wetland Rp-W",
                                     rnat_mmi="Forest/Grass Rp-CAT",
                                     dam_mmi="Dam stor Ws",slope_mmi="Slope*depth",strpwr_mmi="Specific stream power",
                                     hag_mmi="Ag index Rp-S",nhag_mmi="Non-ag index Rp-S",
                                     precip_mmi="Precipitation",tmax_mmi="Max temp",
                                     phdi_mmi="Drought index",
                                     dexcess_mmi="Evaporation indicator",lflow_mmi="Summer flow",
                                     bflow_mmi="Bankfull flow",oelflow_mmi="OE Summer flow",oebflow_mmi="OE Bankfull flow",
                                     xcmgw_mmi="Site-riparian cover index",xinc_mmi="Channel incision",
                                     agr_ept="Agriculture Ws",urb_ept="Developed CAT",imp_ept="Impervious Rp-Cat",
                                     rfor_ept="Forest Rp",
                                     rwet_ept="Wetland Rp-W",
                                     rnat_ept="Forest/Grass Rp-CAT",
                                     dam_ept="Dam stor Ws",slope_ept="Slope*depth", strpwr_ept="Specific stream power",
                                     hag_ept="Ag index Rp-S",nhag_ept="Non-ag index Rp-S",
                                     precip_ept="Precipitation",tmax_ept="Max temp",
                                     phdi_ept="Drought index",
                                     dexcess_ept="Evaporation indicator",lflow_ept="Summer flow",
                                     bflow_ept="Bankfull flow", oelflow_ept="OE Summer flow", oebflow_ept="OE Bankfull flow",
                                     xcmgw_ept="Site-riparian cover index",xinc_ept="Channel incision",
                                     agr_tot="Agriculture Ws",urb_tot="Developed CAT",imp_tot="Impervious Rp-Cat",
                                     graz_tot="Grazing habitat Cat",
                                     rfor_tot="Forest Rp",
                                     rwet_tot="Wetland Rp-W",rnat_tot="Forest/Grass Rp-CAT",
                                     dam_tot="Dam stor Ws",slope_tot="Slope*depth",
                                     strpwr_tot="Specific stream power",
                                     hag_tot="Ag index Rp-S",nhag_tot="Non-ag index Rp-S",
                                     precip_tot="Precipitation",tmax_tot="Max temp",
                                     phdi_tot="Drought index",
                                     dexcess_tot="Evaporation indicator",lflow_tot="Summer flow",
                                     bflow_tot="Bankfull flow", oelflow_tot="OE Summer flow", oebflow_tot="OE Bankfull flow",
                                     tp_tot="TP",tn_tot="TN",sulf_tot="Sulfate", turb_tot="Turbidity",
                                     rbs_tot="Relative bed stability",critd_tot="Critical diameter",meand_tot="Mean diameter",
                                     sand_tot="Sands/fines",
                                     xcmgw_tot="Site-riparian cover index",
                                     xinc_tot="Channel incision",
                                     xfcnat_tot="Instream cover",
                                     hab_tot="Habitat richness",
                                     agr_tntot="Agriculture Ws", urb_tntot="Developed CAT",imp_tntot="Impervious Rp-Cat", dam_tntot="Dam stor Ws",precip_tntot="Precipitation",
                                     phdi_tntot="Drought index",slope_tntot="Slope*depth",strpwr_tntot="Specific stream power",hag_tntot="Ag index Rp-S",nhag_tntot="Non-ag index Rp-S",
                                     rfor_tntot="Forest Rp",rnat_tntot="Forest/Grass Rp-CAT", rwet_tntot="Wetland Rp-W",lflow_tntot="Summer flow",bflow_tntot="Bankfull flow",
                                     oelflow_tntot="OE Summer flow",oebflow_tntot="OE Bankfull flow",
                                     dexcess_tntot="Evaporation indicator",xcmgw_tntot="Site-riparian cover index",
                                     urb_rbstot="Developed CAT",agr_rbstot="Agriculture Ws",imp_rbstot="Impervious Rp-Cat", dam_rbstot="Dam stor Ws",precip_rbstot="Precipitation",
                                     phdi_rbstot="Drought index",
                                     slope_rbstot="Slope*depth",strpwr_rbstot="Specific stream power",hag_rbstot="Ag index Rp-S",nhag_rbstot="Non-ag index Rp-S",
                                     rfor_rbstot="Forest Rp",rnat_rbstot="Forest/Grass Rp-CAT",rwet_rbstot="Wetland Rp-W",
                                     lflow_rbstot="Summer flow",bflow_rbstot="Bankfull flow",
                                     oelflow_rbstot="OE Summer flow",oebflow_rbstot="OE Bankfull flow",
                                     dexcess_rbstot="Evaporation indicator",
                                     xcmgw_rbstot="Site-riparian cover index",
                                     agr_xcmgwtot="Agriculture Ws", urb_xcmgwtot="Developed CAT",imp_xcmgwtot="Impervious Rp-Cat",dam_xcmgwtot="Dam stor Ws",precip_xcmgwtot="Precipitation",
                                     phdi_xcmgwtot="Drought index",slope_xcmgwtot="Slope*depth",strpwr_xcmgwtot="Specific stream power",hag_xcmgwtot="Ag index Rp-S",nhag_xcmgwtot="Non-ag index Rp-S",
                                     rfor_xcmgwtot="Forest Rp", rnat_xcmgwtot="Forest/Grass Rp-CAT",rwet_xcmgwtot="Wetland Rp-W",lflow_xcmgwtot="Summer flow",
                                     oelflow_xcmgwtot="OE Summer flow", dexcess_xcmgwtot="Evaporation indicator",
                                     agr_sulftot="Agriculture Ws", urb_sulftot="Developed CAT", imp_sulftot="Impervious Rp-Cat",dam_sulftot="Dam stor Ws",precip_sulftot="Precipitation",
                                     phdi_sulftot="Drought index",slope_sulftot="Slope*depth",strpwr_sulftot="Specific stream power",hag_sulftot="Ag index Rp-S",nhag_sulftot="Non-ag index Rp-S",
                                     rfor_sulftot="Forest Rp",rnat_sulftot="Forest/Grass Rp-CAT", rwet_sulftot="Wetland Rp-W",lflow_sulftot="Summer flow",bflow_sulftot="Bankfull flow",
                                     oelflow_sulftot="OE Summer flow",oebflow_sulftot="OE Bankfull flow",evap_sulftot="Evaporation indicator",
                                     dexcess_sulftot="Evaporation indicator",xcmgw_sulftot="Site-riparian cover index",
                                     agr_evtot="Agriculture Ws", urb_evtot="Developed CAT",imp_evtot="Impervious Rp-Cat",dam_evtot="Dam stor Ws",precip_evtot="Precipitation",
                                     phdi_evtot="Drought index",slope_evtot="Slope*depth",strpwr_evtot="Specific stream power",hag_evtot="Ag index Rp-S",nhag_evtot="Non-ag index Rp-S",
                                     rfor_evtot="Forest Rp",rnat_evtot="Forest/Grass Rp-CAT", rwet_evtot="Wetland Rp-W",lflow_evtot="Summer flow",bflow_evtot="Bankfull flow",
                                     oelflow_evtot="OE Summer flow",oebflow_evtot="OE Bankfull flow",
                                     agr_lftot="Agriculture Ws", urb_lftot="Developed CAT",imp_lftot="Impervious Rp-Cat",dam_lftot="Dam stor Ws",precip_lftot="Precipitation",
                                     phdi_lftot="Drought index",slope_lftot="Slope*depth",strpwr_lftot="Specific stream power",hag_lftot="Ag index Rp-S",nhag_lftot="Non-ag index Rp-S",
                                     rfor_lftot="Forest Rp",rnat_lftot="Forest/Grass Rp-CAT", rwet_lftot="Wetland Rp-W",
                                     agr_bftot="Agriculture Ws", urb_bftot="Developed CAT",imp_bftot="Impervious Rp-Cat",dam_bftot="Dam stor Ws",precip_bftot="Precipitation",
                                     phdi_bftot="Drought index",slope_bftot="Slope*depth",strpwr_bftot="Specific stream power",hag_bftot="Ag index Rp-S",nhag_bftot="Non-ag index Rp-S",
                                     rfor_bftot="Forest Rp",rnat_bftot="Forest/Grass Rp-CAT", rwet_bftot="Wetland Rp-W",
                                     agr_loelftot="Agriculture Ws", urb_loelftot="Developed CAT",dam_loelftot="Dam stor Ws",precip_loelftot="Precipitation",
                                     phdi_loelftot="Drought index",slope_loelftot="Slope*depth",strpwr_loelftot="Specific stream power",hag_loelftot="Ag index Rp-S",nhag_loelftot="Non-ag index Rp-S",
                                     rfor_loelftot="Forest Rp",rnat_loelftot="Forest/Grass Rp-CAT", rwet_loelftot="Wetland Rp-W",
                                     agr_loebftot="Agriculture Ws", urb_loebftot="Developed CAT",dam_loebftot="Dam stor Ws",precip_loebftot="Precipitation",
                                     phdi_loebftot="Drought index",slope_loebftot="Slope*depth",strpwr_loebftot="Specific stream power",hag_loebftot="Ag index Rp-S",nhag_loebftot="Non-ag index Rp-S",
                                     rfor_loebftot="Forest Rp",rnat_loebftot="Forest/Grass Rp-CAT", rwet_loebftot="Wetland Rp-W",
                                     agr_sptot="Agriculture Ws", urb_sptot="Developed CAT",dam_sptot="Dam stor Ws",precip_sptot="Precipitation",
                                     phdi_sptot="Drought index",slope_sptot="Slope*depth",strpwr_sptot="Specific stream power",hag_sptot="Ag index Rp-S",nhag_sptot="Non-ag index Rp-S",
                                     rfor_sptot="Forest Rp",rnat_sptot="Forest/Grass Rp-CAT", rwet_sptot="Wetland Rp-W"))%>%
    rename(Effects = lhs)
}
